name: Build CLang Image
permissions:
  contents: read
  packages: write
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.platform.host }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: x86_64
            host: ubuntu-latest
            gcc_suffix: manylinux
          - name: arm64
            host: arm64-server
            gcc_suffix: manylinux
          - name: x86_64
            host: ubuntu-latest
            gcc_suffix: muslinux
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Clang.${{ matrix.platform.gcc_suffix }}.${{ matrix.platform.name }}.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.platform.gcc_suffix }}-${{ matrix.platform.name }}:latest